# Blitz

https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

## Tensors
https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

In [1]:
from __future__ import print_function
import torch


In [3]:
x = torch.empty(5,3)

In [4]:
print(x)

tensor([[1.0102e-38, 8.9082e-39, 8.4489e-39],
        [1.0102e-38, 1.0561e-38, 1.0286e-38],
        [1.0653e-38, 1.0469e-38, 9.5510e-39],
        [9.9184e-39, 9.0000e-39, 1.0745e-38],
        [9.6429e-39, 1.0653e-38, 1.0561e-38]])


In [6]:
torch.rand(5,3)

tensor([[0.4928, 0.7439, 0.7287],
        [0.0886, 0.7829, 0.6178],
        [0.5472, 0.2468, 0.3992],
        [0.2031, 0.6022, 0.0064],
        [0.2929, 0.0612, 0.3735]])

In [8]:
torch.zeros(5,3,dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [10]:
x = torch.tensor([5.5,3])

In [11]:
x = x.new_ones(5,3,dtype=torch.double)

In [12]:
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [13]:
x = torch.randn_like(x,dtype=torch.float)

In [14]:
print(x)

tensor([[ 0.1763, -1.6256,  0.9602],
        [ 0.1388, -0.0350, -1.2918],
        [ 0.0152, -0.3988, -0.0023],
        [ 1.3004, -1.1746, -0.0391],
        [ 1.3018, -0.3088,  0.3942]])


In [17]:
print(x.size()), x.size()[0]

torch.Size([5, 3])


(None, 5)

### operations

In [23]:
y = torch.rand(5,3)
x = torch.randn_like(x,dtype=torch.float)
print(y)
print(x)

tensor([[0.1317, 0.0819, 0.5700],
        [0.0869, 0.9051, 0.0368],
        [0.8958, 0.4073, 0.5935],
        [0.6324, 0.5148, 0.7990],
        [0.6173, 0.3271, 0.7570]])
tensor([[-9.2685e-01,  2.3195e-03,  5.2914e-01],
        [-5.0295e-02, -2.6816e-01,  6.5841e-01],
        [ 2.0657e+00, -4.8443e-01, -7.9321e-01],
        [-2.8831e+00,  1.5160e+00, -7.1381e-02],
        [-1.3461e-01, -4.5692e-01,  1.0298e+00]])


In [24]:
print(x)

tensor([[-9.2685e-01,  2.3195e-03,  5.2914e-01],
        [-5.0295e-02, -2.6816e-01,  6.5841e-01],
        [ 2.0657e+00, -4.8443e-01, -7.9321e-01],
        [-2.8831e+00,  1.5160e+00, -7.1381e-02],
        [-1.3461e-01, -4.5692e-01,  1.0298e+00]])


In [25]:
x+y

tensor([[-0.7951,  0.0842,  1.0992],
        [ 0.0366,  0.6369,  0.6952],
        [ 2.9615, -0.0771, -0.1997],
        [-2.2508,  2.0309,  0.7277],
        [ 0.4827, -0.1298,  1.7868]])

In [26]:
x[0]

tensor([-0.9268,  0.0023,  0.5291])

In [27]:
y[0]

tensor([0.1317, 0.0819, 0.5700])

In [28]:
x[0] + y[0]

tensor([-0.7951,  0.0842,  1.0992])

In [30]:
torch.add(x,y)

tensor([[-0.7951,  0.0842,  1.0992],
        [ 0.0366,  0.6369,  0.6952],
        [ 2.9615, -0.0771, -0.1997],
        [-2.2508,  2.0309,  0.7277],
        [ 0.4827, -0.1298,  1.7868]])

In [34]:
result = torch.empty(5,3)
result

tensor([[9.2755e-39, 1.0561e-38, 1.0653e-38],
        [1.0194e-38, 8.9082e-39, 4.2246e-39],
        [1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39]])

In [35]:
torch.add(x,y,out=result)

tensor([[-0.7951,  0.0842,  1.0992],
        [ 0.0366,  0.6369,  0.6952],
        [ 2.9615, -0.0771, -0.1997],
        [-2.2508,  2.0309,  0.7277],
        [ 0.4827, -0.1298,  1.7868]])

In [36]:
result

tensor([[-0.7951,  0.0842,  1.0992],
        [ 0.0366,  0.6369,  0.6952],
        [ 2.9615, -0.0771, -0.1997],
        [-2.2508,  2.0309,  0.7277],
        [ 0.4827, -0.1298,  1.7868]])

In [37]:
y.add_(x)

tensor([[-0.7951,  0.0842,  1.0992],
        [ 0.0366,  0.6369,  0.6952],
        [ 2.9615, -0.0771, -0.1997],
        [-2.2508,  2.0309,  0.7277],
        [ 0.4827, -0.1298,  1.7868]])

In [38]:
y

tensor([[-0.7951,  0.0842,  1.0992],
        [ 0.0366,  0.6369,  0.6952],
        [ 2.9615, -0.0771, -0.1997],
        [-2.2508,  2.0309,  0.7277],
        [ 0.4827, -0.1298,  1.7868]])

In [39]:
print(x[:,1])

tensor([ 0.0023, -0.2682, -0.4844,  1.5160, -0.4569])


In [41]:
#resizing

In [42]:
x = torch.randn(4,4)

In [43]:
y = x.view(16)

In [44]:
z = x.view(-1,8)#size -1 means inferred from other dimensions

In [50]:
x,y,z, x.shape,y.shape,z.shape

(tensor([[ 0.3038,  0.9434, -0.4057,  0.2235],
         [ 1.6839, -0.2747, -0.2567,  1.9961],
         [-1.9706, -0.4221, -0.4148,  0.4611],
         [-0.6299, -1.5453, -1.3101,  1.3056]]),
 tensor([ 0.3038,  0.9434, -0.4057,  0.2235,  1.6839, -0.2747, -0.2567,  1.9961,
         -1.9706, -0.4221, -0.4148,  0.4611, -0.6299, -1.5453, -1.3101,  1.3056]),
 tensor([[ 0.3038,  0.9434, -0.4057,  0.2235,  1.6839, -0.2747, -0.2567,  1.9961],
         [-1.9706, -0.4221, -0.4148,  0.4611, -0.6299, -1.5453, -1.3101,  1.3056]]),
 torch.Size([4, 4]),
 torch.Size([16]),
 torch.Size([2, 8]))

In [52]:
w = x.view(2,-1)

In [53]:
w.shape

torch.Size([2, 8])

In [54]:
#wow~

In [55]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.4063])
1.4062860012054443


In [56]:
a = torch.ones(5)

In [57]:
a

tensor([1., 1., 1., 1., 1.])

In [58]:
b = a.numpy()

In [59]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [64]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [65]:
print(b)

[2. 2. 2. 2. 2.]


In [66]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA

In [67]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([2.4063], device='cuda:0')
tensor([2.4063], dtype=torch.float64)


## AutoGrad

In [68]:
x = torch.ones(2,2, requires_grad = True)

In [69]:
y = x + 2

In [70]:
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [71]:
y.grad_fn

In [73]:
z = y*y *3
out = z.mean()

In [74]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [75]:
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [76]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [77]:
out.backward()

In [78]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [79]:
x = torch.randn(3,requires_grad=True)

In [80]:
y = x*2
while y.data.norm() <1000:
    y=y *2
    
print(y)

tensor([593.2105, -11.7719, 973.4538], grad_fn=<MulBackward0>)


In [81]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [82]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
